TheNextWeb-clone
FrederickMih/TheNextWeb-clone pull request #1
Opened 2020-12-02 15:43 UTC by FrederickMih

We have successfully structured out the next web clone page, including the mobile, tablet, and desktop versions in addition with media queries. As a result of this, we need some feedbacks in order to improve the look of our page.

2020-12-02 17:07 UTC, arslanbisharat requested changes
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**

- [ ]  **Commented Code:** Please remove commented code from your project. It is not a good practice to write commented code in your project. Please keep it clean as much as possible. 

- [ ] Please use semantic HTML. You are missing the **main** and **footer** tags. 
- [ ] [Optional] Please add your CSS files into a single folder and then add your assets and CSS folder in one single folder. This will help you to make your project clean. 

- [ ] **Linter**: Please remove Linter errors.

- [ ] You have too many empty rules in CSS files. Please remove them. 
### Desktop
- [ ] You have unnecessary white space before the navbar. Please remove that white space. 
![chrome-capture (9)](https://user-images.githubusercontent.com/58504655/100899898-20a7fc80-34e4-11eb-9ee5-6a6a20b75ab6.jpg)

- [ ] You are missing the TNW logo on the Desktop version from the left big image. Please work on it. 
![chrome-capture (10)](https://user-images.githubusercontent.com/58504655/100904188-957d3580-34e8-11eb-983c-9e503b9aaff6.jpg)

- [ ] Please move the text and other content down as present on the original page. 
![chrome-capture (11)](https://user-images.githubusercontent.com/58504655/100904380-cb221e80-34e8-11eb-8731-bc9fcbbb4a0f.jpg)

- [ ] Please move the items from left to the right side opposite to the` Latest funding rounds on Index.co
`
![chrome-capture (12)](https://user-images.githubusercontent.com/58504655/100904680-0de3f680-34e9-11eb-8f36-4a3df87559ef.jpg)

- [ ] Please make the navbar sticky on scrolling as present on the original page. 

- [ ] Please correct the path of the images. The images are not rendering because of the wrong path.  You must add ./ before a path declaration. 

![chrome-capture (13)](https://user-images.githubusercontent.com/58504655/100904932-57344600-34e9-11eb-8d16-6c7fda5cc2c3.jpg)

- [ ] Please add different content (headings and other text including images) for the whole page. This will make your project outstanding. 

### Medium

- [ ] TWN logo appears at the leftmost part on navbar but that part is missing in your clone. Please work on it. 

![chrome-capture (14)](https://user-images.githubusercontent.com/58504655/100905448-e6d9f480-34e9-11eb-9bff-b059f58a27e2.jpg)

### SMALL

- [ ] The TNW logo on small doesn't match the one present on the original page. Please work on it. 


**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

2020-12-02 17:07 UTC, arslanbisharat commented on README.md
> +This project is [MIT](lic.url) licensed.
- [ ] **Wrong Path**: Please add the path to the License. You don't have any URL right now.

2020-12-02 17:07 UTC, arslanbisharat commented on README.md
> +> This project is the clone of the next web page
- [ ] **More Information:** Please add more details about your project here. Please tell us why you created this project and how you did it.

2020-12-02 17:07 UTC, arslanbisharat commented on README.md
> +![screenshot](./assets/images/thenextweb.png)
- [ ] [Optional] You can add screenshots from different screen-sizes to showcase your project effectively.

2020-12-02 17:07 UTC, arslanbisharat commented on header.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project. It is not a good practice to write commented code in your project. Please keep it clean as much as possible.

2020-12-02 17:07 UTC, arslanbisharat commented on header.css
> +  /* position: relative; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on header.css
> +  /* position: absolute; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on header.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on header.css
> +  /* border: 1px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on header.css
> +    /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on tablet.css
> +        /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on tablet.css
> +        /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on tablet.css
> +        /* grid-template-rows: repear(3, 1fr); */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on index.html
> +                <!-- <div class="logo"><img src="assets/icons/tnw.svg" alt="TNW logo"></div> -->
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 5px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 3px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red;   */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* background-color: yellow; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 5px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> + /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blueviolet; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blueviolet; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 3px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 2px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid green; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid red; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-02 17:07 UTC, arslanbisharat commented on style.css
> +  /* border: 1px solid blue; */
- [ ] **Commented Code:** Please remove commented code from your project.

2020-12-03 18:16 UTC, jubaan requested changes
# Status: Changes Required :recycle: 

There are some issues that need to be addressed before we can move forward. Please review the list below.

## Required changes :wrench: 
### [Mandatory] :red_circle: 

- [ ] Customize readme with information specific to your project. The Getting started section has no relevant information about how to get started with this specific proyect.
![image](https://user-images.githubusercontent.com/25774518/101068052-e54a1400-355d-11eb-949e-06d63212df3e.png)

- [ ] The live demo link is not working on the README. Link is broken.

- [ ] Images are not displaying.  Please correct the path of the images. The images are not rendering because of the wrong path. You must add `./` before a path declaration on the HTML and CSS files.
![image](https://user-images.githubusercontent.com/25774518/101069705-f98f1080-355f-11eb-8132-a3b18cced675.png)
![image](https://user-images.githubusercontent.com/25774518/101069802-19becf80-3560-11eb-93db-8da1f8d93092.png)

- [ ] Tablet view should go from 768px to 426px. 

- [ ]  The TNW logo in the 3 image section is still not displaying

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-12-03 20:17 UTC, descholar-ceo commented
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

2020-12-03 20:41 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @KumarAmitt and @FrederickMih  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes in your readme file to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The license link from your readme file doesn't exists
- [ ] The issues link you provided in your readme file doesn't work, it should be fixed before requesting another review
- [ ] The linkedin profile link of Amit Kumar provided in your readme file doesn't work, it should be fixed before requesting another review
- [ ] In the `Getting started section` from your readme file there are some steps which are not clear users who are not already familiar with git/github, read below text and improve it by answering the questions I put:`

```bash
Setup
See the product documentation for installation and get running. => This sentence is not clear, which product should a user read its docs, and where to find those docs? My Suggestion: I don't see any point to put this sentence, you can just remove it.

Usage
Clone the folder on your local machine. => How should a user clone that folder? Is it really a folder that I should clone? (Answer: It's a repository instead), so then specify which command a user should run to clone this repository.

```

# [Optional changes] :yellow_circle: 

- [ ] The top three articles are taking a big height, please reduce their height and so that they will look exactly like the original version

:warning: Your commit messages should be consistently in imperative mode or present tense, _i.e.:_ you should have written `Fix CSS linter errors` instead of writing `Fixing CSS linter errors`, refer [to this article for more details on how to write a good && professional commit message](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2020-12-04 06:41 UTC, mimipeshy commented
## STATUS: APPROVED 🥳  🍾 🕺  

Hey Team @KumarAmitt and  @FrederickMih 👋 👋 , congratulations on working so hard on this project. Good job on working on all the feedback given by all TSE's. You are on your way to becoming a world-class developer 👩‍💻 . Go ahead and merge.
All the best in future projects.

Regards
Peris Ndanu

2020-12-04 07:47 UTC, merged